ui: tape
browsers:
  - name: chrome
    version: latest
    os: 'Mac 10.11'
  - name: firefox
    version: latest
    os: 'Mac 10.11'
  - name: microsoftedge
    version: latest
  - name: safari
    version: latest
    os: 'Mac 10.11'
  - name: iphone
    version: '8.4..9.2'
  - name: android
    version: '5.1'
  - name: opera
    version: latest
    platform: 'Windows 10'
concurrency: 2
tunnel:
  type: ngrok
  bind_tls: true
browserify:
  - transform: yo-yoify
  - transform: sheetify/transform
  - transform: babelify
