ui: tape
browserify:
  - transform: sheetify/transform
  - transform: babelify
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: ie
    version: -1..latest
